# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-08 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20200208_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boy_friend',
        ),
    ]
