# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20200209_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
