# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-13 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_user_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='images',
        ),
    ]
