# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_remove_user_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='post',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
