# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-14 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_post',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
