# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_auto_20200218_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_post',
            old_name='all',
            new_name='post1',
        ),
        migrations.AddField(
            model_name='all_post',
            name='image1',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
