# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_auto_20200218_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_post',
            name='time1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
