# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_all_post_time1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.User_Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='all_post',
            name='user',
        ),
        migrations.DeleteModel(
            name='All_Post',
        ),
    ]
