# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-21 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0023_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
