# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0025_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App1.User_Post'),
            preserve_default=False,
        ),
    ]
