# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0028_auto_20200223_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_message',
            name='sender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
